/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SpectraRouteImport } from './routes/spectra'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ModelagemRouteImport } from './routes/modelagem'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstrucoesRouteImport } from './routes/instrucoes'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as GeradorRouteImport } from './routes/gerador'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AnalisesAndamentoRouteImport } from './routes/analises-andamento'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpectraIndexRouteImport } from './routes/spectra.index'
import { Route as ModelagemIndexRouteImport } from './routes/modelagem.index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets.index'
import { Route as CollectionIndexRouteImport } from './routes/collection.index'
import { Route as SpectraIdRouteImport } from './routes/spectra.$id'
import { Route as PerfilEditarRouteImport } from './routes/perfil.editar'
import { Route as ModelagemNovoRouteImport } from './routes/modelagem.novo'
import { Route as ModelagemIdRouteImport } from './routes/modelagem.$id'
import { Route as DatasetsIdRouteImport } from './routes/datasets.$id'
import { Route as CollectionIdRouteImport } from './routes/collection.$id'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectraRoute = SpectraRouteImport.update({
  id: '/spectra',
  path: '/spectra',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelagemRoute = ModelagemRouteImport.update({
  id: '/modelagem',
  path: '/modelagem',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrucoesRoute = InstrucoesRouteImport.update({
  id: '/instrucoes',
  path: '/instrucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorRoute = GeradorRouteImport.update({
  id: '/gerador',
  path: '/gerador',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisesAndamentoRoute = AnalisesAndamentoRouteImport.update({
  id: '/analises-andamento',
  path: '/analises-andamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectraIndexRoute = SpectraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpectraRoute,
} as any)
const ModelagemIndexRoute = ModelagemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelagemRoute,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DatasetsRoute,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectraIdRoute = SpectraIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpectraRoute,
} as any)
const PerfilEditarRoute = PerfilEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => PerfilRoute,
} as any)
const ModelagemNovoRoute = ModelagemNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ModelagemRoute,
} as any)
const ModelagemIdRoute = ModelagemIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ModelagemRoute,
} as any)
const DatasetsIdRoute = DatasetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DatasetsRoute,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/analises-andamento': typeof AnalisesAndamentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/gerador': typeof GeradorRoute
  '/historico': typeof HistoricoRoute
  '/home': typeof HomeRoute
  '/instrucoes': typeof InstrucoesRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/modelagem': typeof ModelagemRouteWithChildren
  '/perfil': typeof PerfilRouteWithChildren
  '/spectra': typeof SpectraRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/collection/$id': typeof CollectionIdRoute
  '/datasets/$id': typeof DatasetsIdRoute
  '/modelagem/$id': typeof ModelagemIdRoute
  '/modelagem/novo': typeof ModelagemNovoRoute
  '/perfil/editar': typeof PerfilEditarRoute
  '/spectra/$id': typeof SpectraIdRoute
  '/collection/': typeof CollectionIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/modelagem/': typeof ModelagemIndexRoute
  '/spectra/': typeof SpectraIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/analises-andamento': typeof AnalisesAndamentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/gerador': typeof GeradorRoute
  '/historico': typeof HistoricoRoute
  '/home': typeof HomeRoute
  '/instrucoes': typeof InstrucoesRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/collection/$id': typeof CollectionIdRoute
  '/datasets/$id': typeof DatasetsIdRoute
  '/modelagem/$id': typeof ModelagemIdRoute
  '/modelagem/novo': typeof ModelagemNovoRoute
  '/perfil/editar': typeof PerfilEditarRoute
  '/spectra/$id': typeof SpectraIdRoute
  '/collection': typeof CollectionIndexRoute
  '/datasets': typeof DatasetsIndexRoute
  '/modelagem': typeof ModelagemIndexRoute
  '/spectra': typeof SpectraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/analises-andamento': typeof AnalisesAndamentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/gerador': typeof GeradorRoute
  '/historico': typeof HistoricoRoute
  '/home': typeof HomeRoute
  '/instrucoes': typeof InstrucoesRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/modelagem': typeof ModelagemRouteWithChildren
  '/perfil': typeof PerfilRouteWithChildren
  '/spectra': typeof SpectraRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/collection/$id': typeof CollectionIdRoute
  '/datasets/$id': typeof DatasetsIdRoute
  '/modelagem/$id': typeof ModelagemIdRoute
  '/modelagem/novo': typeof ModelagemNovoRoute
  '/perfil/editar': typeof PerfilEditarRoute
  '/spectra/$id': typeof SpectraIdRoute
  '/collection/': typeof CollectionIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/modelagem/': typeof ModelagemIndexRoute
  '/spectra/': typeof SpectraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise'
    | '/analises-andamento'
    | '/configuracoes'
    | '/datasets'
    | '/gerador'
    | '/historico'
    | '/home'
    | '/instrucoes'
    | '/login'
    | '/mobile'
    | '/modelagem'
    | '/perfil'
    | '/spectra'
    | '/suporte'
    | '/collection/$id'
    | '/datasets/$id'
    | '/modelagem/$id'
    | '/modelagem/novo'
    | '/perfil/editar'
    | '/spectra/$id'
    | '/collection/'
    | '/datasets/'
    | '/modelagem/'
    | '/spectra/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise'
    | '/analises-andamento'
    | '/configuracoes'
    | '/gerador'
    | '/historico'
    | '/home'
    | '/instrucoes'
    | '/login'
    | '/mobile'
    | '/perfil'
    | '/suporte'
    | '/collection/$id'
    | '/datasets/$id'
    | '/modelagem/$id'
    | '/modelagem/novo'
    | '/perfil/editar'
    | '/spectra/$id'
    | '/collection'
    | '/datasets'
    | '/modelagem'
    | '/spectra'
  id:
    | '__root__'
    | '/'
    | '/analise'
    | '/analises-andamento'
    | '/configuracoes'
    | '/datasets'
    | '/gerador'
    | '/historico'
    | '/home'
    | '/instrucoes'
    | '/login'
    | '/mobile'
    | '/modelagem'
    | '/perfil'
    | '/spectra'
    | '/suporte'
    | '/collection/$id'
    | '/datasets/$id'
    | '/modelagem/$id'
    | '/modelagem/novo'
    | '/perfil/editar'
    | '/spectra/$id'
    | '/collection/'
    | '/datasets/'
    | '/modelagem/'
    | '/spectra/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseRoute: typeof AnaliseRoute
  AnalisesAndamentoRoute: typeof AnalisesAndamentoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DatasetsRoute: typeof DatasetsRouteWithChildren
  GeradorRoute: typeof GeradorRoute
  HistoricoRoute: typeof HistoricoRoute
  HomeRoute: typeof HomeRoute
  InstrucoesRoute: typeof InstrucoesRoute
  LoginRoute: typeof LoginRoute
  MobileRoute: typeof MobileRoute
  ModelagemRoute: typeof ModelagemRouteWithChildren
  PerfilRoute: typeof PerfilRouteWithChildren
  SpectraRoute: typeof SpectraRouteWithChildren
  SuporteRoute: typeof SuporteRoute
  CollectionIdRoute: typeof CollectionIdRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectra': {
      id: '/spectra'
      path: '/spectra'
      fullPath: '/spectra'
      preLoaderRoute: typeof SpectraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelagem': {
      id: '/modelagem'
      path: '/modelagem'
      fullPath: '/modelagem'
      preLoaderRoute: typeof ModelagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrucoes': {
      id: '/instrucoes'
      path: '/instrucoes'
      fullPath: '/instrucoes'
      preLoaderRoute: typeof InstrucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador': {
      id: '/gerador'
      path: '/gerador'
      fullPath: '/gerador'
      preLoaderRoute: typeof GeradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analises-andamento': {
      id: '/analises-andamento'
      path: '/analises-andamento'
      fullPath: '/analises-andamento'
      preLoaderRoute: typeof AnalisesAndamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectra/': {
      id: '/spectra/'
      path: '/'
      fullPath: '/spectra/'
      preLoaderRoute: typeof SpectraIndexRouteImport
      parentRoute: typeof SpectraRoute
    }
    '/modelagem/': {
      id: '/modelagem/'
      path: '/'
      fullPath: '/modelagem/'
      preLoaderRoute: typeof ModelagemIndexRouteImport
      parentRoute: typeof ModelagemRoute
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof DatasetsRoute
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectra/$id': {
      id: '/spectra/$id'
      path: '/$id'
      fullPath: '/spectra/$id'
      preLoaderRoute: typeof SpectraIdRouteImport
      parentRoute: typeof SpectraRoute
    }
    '/perfil/editar': {
      id: '/perfil/editar'
      path: '/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof PerfilEditarRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/modelagem/novo': {
      id: '/modelagem/novo'
      path: '/novo'
      fullPath: '/modelagem/novo'
      preLoaderRoute: typeof ModelagemNovoRouteImport
      parentRoute: typeof ModelagemRoute
    }
    '/modelagem/$id': {
      id: '/modelagem/$id'
      path: '/$id'
      fullPath: '/modelagem/$id'
      preLoaderRoute: typeof ModelagemIdRouteImport
      parentRoute: typeof ModelagemRoute
    }
    '/datasets/$id': {
      id: '/datasets/$id'
      path: '/$id'
      fullPath: '/datasets/$id'
      preLoaderRoute: typeof DatasetsIdRouteImport
      parentRoute: typeof DatasetsRoute
    }
    '/collection/$id': {
      id: '/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DatasetsRouteChildren {
  DatasetsIdRoute: typeof DatasetsIdRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
}

const DatasetsRouteChildren: DatasetsRouteChildren = {
  DatasetsIdRoute: DatasetsIdRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
}

const DatasetsRouteWithChildren = DatasetsRoute._addFileChildren(
  DatasetsRouteChildren,
)

interface ModelagemRouteChildren {
  ModelagemIdRoute: typeof ModelagemIdRoute
  ModelagemNovoRoute: typeof ModelagemNovoRoute
  ModelagemIndexRoute: typeof ModelagemIndexRoute
}

const ModelagemRouteChildren: ModelagemRouteChildren = {
  ModelagemIdRoute: ModelagemIdRoute,
  ModelagemNovoRoute: ModelagemNovoRoute,
  ModelagemIndexRoute: ModelagemIndexRoute,
}

const ModelagemRouteWithChildren = ModelagemRoute._addFileChildren(
  ModelagemRouteChildren,
)

interface PerfilRouteChildren {
  PerfilEditarRoute: typeof PerfilEditarRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilEditarRoute: PerfilEditarRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

interface SpectraRouteChildren {
  SpectraIdRoute: typeof SpectraIdRoute
  SpectraIndexRoute: typeof SpectraIndexRoute
}

const SpectraRouteChildren: SpectraRouteChildren = {
  SpectraIdRoute: SpectraIdRoute,
  SpectraIndexRoute: SpectraIndexRoute,
}

const SpectraRouteWithChildren =
  SpectraRoute._addFileChildren(SpectraRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseRoute: AnaliseRoute,
  AnalisesAndamentoRoute: AnalisesAndamentoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DatasetsRoute: DatasetsRouteWithChildren,
  GeradorRoute: GeradorRoute,
  HistoricoRoute: HistoricoRoute,
  HomeRoute: HomeRoute,
  InstrucoesRoute: InstrucoesRoute,
  LoginRoute: LoginRoute,
  MobileRoute: MobileRoute,
  ModelagemRoute: ModelagemRouteWithChildren,
  PerfilRoute: PerfilRouteWithChildren,
  SpectraRoute: SpectraRouteWithChildren,
  SuporteRoute: SuporteRoute,
  CollectionIdRoute: CollectionIdRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
